volumes:
    uploads:
        driver: local
    logs:
        driver: local
    mysql:
        driver: local
    vendor:
        driver: local
    resources:
        driver: local
    menubar:
        driver: local
    header:
        driver: local

networks:
    app_net:


services:
    mysql:
        image: mariadb:10.5
        container_name: mysql
        restart: always
        expose:
            - "3306"
        networks:
            - app_net
        volumes:
            - ./app/Database/tables.sql:/docker-entrypoint-initdb.d/01_tables.sql
            - ./app/Database/constraints.sql:/docker-entrypoint-initdb.d/02_constraints.sql
            - ./app/Database/docker_mysql.cnf:/etc/mysql/conf.d/ospos.cnf:ro
            - mysql:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=pointofsale
            - MYSQL_DATABASE=ospos
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=pointofsale
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s
    ospos:
        build:
            context: .
            args:
                - USERID=${USERID}
                - GROUPID=${GROUPID}
            target: ospos_dev
        container_name: ospos_dev
        restart: always
        user: "${USERID}:${GROUPID}"
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8010:80"
        networks:
            - app_net
        volumes:
            - .:/app
            - vendor:/app/vendor
            - resources:/app/public/resources
            - menubar:/app/public/images/menubar
            - header:/app/app/Views/partial
        environment:
            - CI_ENVIRONMENT=development
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql
            - PHP_TIMEZONE=UTC
            - XDEBUG_CONFIG=client_host=172.17.0.1
            - ENCRYPTION_KEY=hex2bin:57cd572ac23419d889bf423630c7b37ceb584f2456c14e558e95947d1a510f19
